Repository taed2-2425q1-gced-upc/TAED2_Mates, pull requests merged in 2024-10, with the labels that each got.

#8 Pull into main feature/cards
  docs/Competition_models.png
  docs/Competition_results.png
  docs/Dataset_card.md
  docs/imbalanced_dataset.png
Labels: documentation

#11 Pull into main feature/pipelines
  .gitignore
  data/processed/.gitignore
  docs/Model_card.md
  dvc.lock
  dvc.yaml
  mates/config.py
  mates/dataset.py
  mates/features.py
  mates/modeling/predict.py
  mates/modeling/prepare.py
  mates/modeling/train.py
  metrics/mobilenet_batch_32_adam_emissions.csv
  metrics/mobilenet_batch_32_emissions.csv
  metrics/mobilenet_batch_32_rmsprop_emissions.csv
  metrics/mobilenet_batch_64_emissions.csv
  metrics/mobilenet_test_emissions.csv
  mlruns/0/meta.yaml
  models/.gitkeep
  params.yaml
  poetry.lock
  pyproject.toml
Labels: enhancement

#14 added tests, fixed read_data and added test to makefile
  Makefile
  mates/features.py
  pyproject.toml
  tests/test_create_batches.py
  tests/test_create_model.py
  tests/test_get_label.py
  tests/test_load_model.py
  tests/test_load_params.py
  tests/test_load_processed_data.py
  tests/test_model.py
  tests/test_prepare.py
  tests/test_process_image.py
  tests/test_read_data.py
Labels: enhancement

#15 Pull into main fix/model
  dvc.lock
  mates/config.py
  mates/modeling/train.py
  metrics/mobilenet_batch_32_adam_emissions.csv
  metrics/mobilenet_batch_32_emissions.csv
  metrics/mobilenet_batch_32_rmsprop_emissions.csv
  metrics/mobilenet_batch_64_emissions.csv
  metrics/mobilenet_exp_batch_32_emissions.csv
  metrics/mobilenet_exp_batch_62_emissions.csv
  metrics/mobilenet_test_emissions.csv
  mlruns/0/meta.yaml
  params.yaml
Labels: bug

#16 Pull into main feature/api
  poetry.lock
  pyproject.toml
Labels: documentation

#19 Pull into main fix/predict
  mates/modeling/predict.py
Labels: bug

#21 Pull into main fix/security
  poetry.lock
  pyproject.toml
Labels: bug

#23 Pull into main feature/gaissa
  data/output/gaissa_log.txt
  data/output/gaissa_mobilenet_exp_batch_62.csv
  reports/gaissa/calculator.py
  reports/gaissa/gaissaplugin.py
  reports/gaissa/main_script.py
  reports/gaissa/plugin_interface.py
Labels: documentation

#25 Pull into main feature/readmedocs
  README.md
  data/README.md
  docs/README.md
  mates/README.md
  metrics/README.md
  models/README.md
  notebooks/README.md
  reports/README.md
  tests/README.md
Labels: documentation

#26 Feature/tests
  Makefile
  mates/features/features.py
  mates/features/utils.py
  pyproject.toml
  tests/bit.jpg
  tests/pod.jpg
  tests/test_api.py
  tests/test_create_batches.py
  tests/test_create_model.py
  tests/test_get_label.py
  tests/test_load_model.py
  tests/test_load_params.py
  tests/test_load_processed_data.py
  tests/test_model.py
  tests/test_predict.py
  tests/test_predict_single.py
  tests/test_prepare.py
  tests/test_process_image.py
  tests/test_read_data.py
  tests/test_read_labels.py
  tests/tests-report.xml
Labels: enhancement

#28 Pull into main fix/lint
  Makefile
  linter.txt
  mates/app/api.py
  mates/config.py
  mates/features/deepchecks.py
  mates/features/features.py
  mates/features/gaissa/calculator.py
  mates/features/gaissa/gaissaplugin.py
  mates/features/gaissa/main_script.py
  mates/features/gaissa/plugin_interface.py
  mates/features/utils.py
  mates/modeling/predict.py
  mates/modeling/prepare.py
  mates/modeling/train.py
  mates/streamlit.py
  poetry.lock
  tests/test_api.py
  tests/test_create_batches.py
  tests/test_create_model.py
  tests/test_get_label.py
  tests/test_load_model.py
  tests/test_load_params.py
  tests/test_load_processed_data.py
  tests/test_model.py
  tests/test_predict.py
  tests/test_predict_single.py
  tests/test_prepare.py
  tests/test_process_image.py
  tests/test_read_data.py
  tests/test_read_labels.py
  tests/tests-report.xml
Labels: bug

#31 test fix
  mates/config.py
  mates/features/features.py
  tests/test_images/0021f9ceb3235effd7fcde7f7538ed62.jpg
  tests/test_images/008887054b18ba3c7601792b6a453cc3.jpg
  tests/test_images/00e9ed3fab1d2032603d1a90e557976f.jpg
  tests/test_images/010d65bd29d246aea53d9849da142ccf.jpg
  tests/test_images/0120343862761d052d6a7ade81625c94.jpg
  tests/test_images/0161847d5bfae154af084993fa26a1a7.jpg
  tests/test_images/0311a6a51a414ba91f3ad8055170baa1.jpg
  tests/test_images/0365fe4e3e13a885c6b02ebbbf2d9173.jpg
  tests/test_images/03ae71ff9e4c5ac97afdfa956ea5e191.jpg
  tests/test_images/03f6435dc8a5e760d19e67831c6034fb.jpg
  tests/test_model.py
  tests/test_predict.py
  tests/test_predict_single.py
Labels: bug

#32 added workflows
  .github/workflows/pylint.yml
  .github/workflows/pytest.yml
Labels: enhancement

#24 Pull into main feature/cards
  READMEs/metricsREADME.md
  READMEs/testsREADME.md
  data/README.md
  docs/Competition_models.png
  docs/Competition_results.png
  docs/Dataset_card.md
  docs/Model_card.md
  docs/README.md
  docs/notebook_emission.ipynb
  mates/README.md
  models/README.md
  models/emissions_image.png
  notebooks/README.md
  reports/README.md
  reports/figures/example_image2.jpg
Labels: documentation

#33 Pull into main fix/docs
  README.md
  docs/Dataset_card.md
  docs/Model_card.md
  reports/figures/dataset_card_example2.jpg
Labels: documentation, enhancement

#34 Pull into main fix/train
  mates/modeling/train.py
  metrics/README.md
  metrics/adam_32_emissions.csv
  metrics/adam_62_emissions.csv
  metrics/adamw_32_emissions.csv
  metrics/adamw_62_emissions.csv
  metrics/mobilenet_exp_batch_32_emissions.csv
  metrics/mobilenet_exp_batch_62_emissions.csv
  metrics/rmsprop_32_emissions.csv
  metrics/rmsprop_62_emissions.csv
  metrics/sgd_32_emissions.csv
  metrics/sgd_62_emissions.csv
  params.yaml
Labels: enhancement

#36 Pull into main fix/tests
  pyproject.toml
  tests/test_api.py
  tests/test_images/0021f9ceb3235effd7fcde7f7538ed62.jpg
  tests/test_images/008887054b18ba3c7601792b6a453cc3.jpg
  tests/test_images/00e9ed3fab1d2032603d1a90e557976f.jpg
  tests/test_images/010d65bd29d246aea53d9849da142ccf.jpg
  tests/test_images/0120343862761d052d6a7ade81625c94.jpg
  tests/test_images/0161847d5bfae154af084993fa26a1a7.jpg
  tests/test_images/0311a6a51a414ba91f3ad8055170baa1.jpg
  tests/test_images/0365fe4e3e13a885c6b02ebbbf2d9173.jpg
  tests/test_images/03ae71ff9e4c5ac97afdfa956ea5e191.jpg
  tests/test_images/03f6435dc8a5e760d19e67831c6034fb.jpg
  tests/test_images/bit.jpg
  tests/test_images/img1.jpg
  tests/test_images/img10.jpg
  tests/test_images/img2.jpg
  tests/test_images/img3.jpg
  tests/test_images/img4.jpg
  tests/test_images/img5.jpg
  tests/test_images/img6.jpg
  tests/test_images/img7.jpg
  tests/test_images/img8.jpg
  tests/test_images/img9.jpg
  tests/test_images/pod.jpg
  tests/test_predict_single.py
  tests/tests-report.xml
Labels: bug

#35 Pull into main fix/readmes
  tests/README.md
Labels: documentation, enhancement

#40 Pull into main fix/actions
  .github/workflows/pytest.yml
  mates/features/features.py
  mates/modeling/prepare.py
  mates/modeling/train.py
  tests/test_load_processed_data.py
  tests/test_model.py
  tests/test_predict.py
  tests/test_prepare.py
Labels: bug
