Repository taed2-2425q1-gced-upc/TAED2_Mates, pull requests merged in 2024-09, with the labels that each got.

#3 Pull into main feature/cards
  docs/Dataset_card.md
  docs/example_image.jpg
  models/Model_card.md
Labels: documentation

#6 Pull into main fix/dvc_data
  .dvc/config
  .gitignore
  data.dvc
  notebooks/model_exploration.ipynb
Labels: bug

#7 Pull into main experiment/eda
  data/external/.gitkeep
  data/interim/.gitkeep
  data/processed/.gitkeep
  data/raw/.gitkeep
  notebooks/dataset_exploration.ipynb
  notebooks/model_exploration.ipynb
Labels: documentation

#10 Pull into main feature/pipelines
  data/.gitignore
  dvc.yaml
  mates/config.py
  mates/features.py
  mates/modeling/prepare.py
  mates/modeling/train.py
  params.yaml
Labels: enhancement
